'a' = '2'
'an' = '3'
'the' = '4'
'der' = '4'
'die' = '4'
'das' = '4'
'le' = '3'
'la' = '3'
'les' = '4'
'l' = '2'
'il' = '3'
'lo' = '3'
"l'" = '2'
'gli' = '4'
'gl' = '3'
'el' = '3'
'los' = '4'
'las' = '4'
'den' = '4'
'det' = '4'
'de' = '3'