[explain]
url = "https://na91.alma.exlibrisgroup.com/view/sru/01NAL_INST"

[searchRetrieve]
record_schema = "marcxml"
url = "https://na91.alma.exlibrisgroup.com/view/sru/01NAL_INST"
output_format = "pymarc"
query1 = "alma.issn=1365-6937" # 2 records
query2 = "alma.creator=crossref" # 1 record
query3 = "alma.title=pothos" #46 records